/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as GraphicsRouteImport } from './routes/graphics'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarsRouteImport } from './routes/calendars'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIdRouteImport } from './routes/work/$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRoute = GraphicsRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsRoute = CalendarsRouteImport.update({
  id: '/calendars',
  path: '/calendars',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdRoute = WorkIdRouteImport.update({
  id: '/work/$id',
  path: '/work/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads': typeof AdsRoute
  '/calendars': typeof CalendarsRoute
  '/clients': typeof ClientsRoute
  '/gallery': typeof GalleryRoute
  '/graphics': typeof GraphicsRoute
  '/videos': typeof VideosRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads': typeof AdsRoute
  '/calendars': typeof CalendarsRoute
  '/clients': typeof ClientsRoute
  '/gallery': typeof GalleryRoute
  '/graphics': typeof GraphicsRoute
  '/videos': typeof VideosRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads': typeof AdsRoute
  '/calendars': typeof CalendarsRoute
  '/clients': typeof ClientsRoute
  '/gallery': typeof GalleryRoute
  '/graphics': typeof GraphicsRoute
  '/videos': typeof VideosRoute
  '/work/$id': typeof WorkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ads'
    | '/calendars'
    | '/clients'
    | '/gallery'
    | '/graphics'
    | '/videos'
    | '/work/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ads'
    | '/calendars'
    | '/clients'
    | '/gallery'
    | '/graphics'
    | '/videos'
    | '/work/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ads'
    | '/calendars'
    | '/clients'
    | '/gallery'
    | '/graphics'
    | '/videos'
    | '/work/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdsRoute: typeof AdsRoute
  CalendarsRoute: typeof CalendarsRoute
  ClientsRoute: typeof ClientsRoute
  GalleryRoute: typeof GalleryRoute
  GraphicsRoute: typeof GraphicsRoute
  VideosRoute: typeof VideosRoute
  WorkIdRoute: typeof WorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars': {
      id: '/calendars'
      path: '/calendars'
      fullPath: '/calendars'
      preLoaderRoute: typeof CalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/work/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdsRoute: AdsRoute,
  CalendarsRoute: CalendarsRoute,
  ClientsRoute: ClientsRoute,
  GalleryRoute: GalleryRoute,
  GraphicsRoute: GraphicsRoute,
  VideosRoute: VideosRoute,
  WorkIdRoute: WorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
